VLOG=vlog
VCOM=vcom
VSIM=vsim
QRUN=qrun
SOURCE_PATH=../..
SWITCHES= -modelsimini /opt/tools/Questa/questa_sim_libs/modelsim.ini -suppress 10016 -incr -mfcu -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_19 -L xilinx_vip -work xil_defaultlib
LIBS= -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_19 -L zynq_ultra_ps_e_vip_v1_0_19 -L axi_bram_ctrl_v4_1_11 -L blk_mem_gen_v8_4_9 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L xlconstant_v1_1_9 -L smartconnect_v1_0 -L axi_register_slice_v2_1_33 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm
COMPILATION_BASE=+incdir+$(SOURCE_PATH)/Base/src +incdir+$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ipshared/ec67/hdl +incdir+$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ipshared/6f8f/hdl +incdir+$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ipshared/3cbc +incdir+$(SOURCE_PATH)/Base/vivado/bd/design_1/ipshared/f0b6/hdl/verilog +incdir+$(SOURCE_PATH)/Base/vivado/bd/design_1/ipshared/0127/hdl/verilog +incdir+$(SOURCE_PATH)/Base/vivado/bd/design_1/ipshared/ec67/hdl +incdir+/applicsqum/xilinx/vivado/2024_2/Vivado/2024.2/data/xilinx_vip/include \
$(SOURCE_PATH)/Base/src/pl_controller.vhd \
$(SOURCE_PATH)/Base/src/axi_mm_master.v \
$(SOURCE_PATH)/Base/src/sync_fifo.v \
$(SOURCE_PATH)/Base/src/sync_fifo_asymm.v \
$(SOURCE_PATH)/Base/src/antenna.sv \
$(SOURCE_PATH)/Base/src/bytes_counter.sv \
$(SOURCE_PATH)/Base/src/control.sv \
$(SOURCE_PATH)/Base/src/data_width_converter.sv \
$(SOURCE_PATH)/Base/src/tasks/task_1/task_1.sv \
$(SOURCE_PATH)/Base/src/tasks/task_10/task_10.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_10_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_11/task_11.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_11_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_12/task_12.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_12_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_13/task_13.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_13_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_14/task_14.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_14_wrapper.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_1_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_2/task_2.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_2_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_3/task_3.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_3_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_4/task_4.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_4_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_5/task_5.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_5_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_6/task_6.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_6_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_7/task_7.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_7_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_8/task_8.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_8_wrapper.sv \
$(SOURCE_PATH)/Base/src/tasks/task_9/task_9.sv \
$(SOURCE_PATH)/Base/src/task_wrappers/task_9_wrapper.sv \
$(SOURCE_PATH)/Base/src/task_deserializer.sv \
$(SOURCE_PATH)/Base/src/task_in.sv \
$(SOURCE_PATH)/Base/src/task_latency_meas.sv \
$(SOURCE_PATH)/Base/src/task_manager.sv \
$(SOURCE_PATH)/Base/src/task_out.sv \
$(SOURCE_PATH)/Base/src/task_serializer.sv \
$(SOURCE_PATH)/Base/src/control_wrapper.v \
$(SOURCE_PATH)/Base/src/control_regs_S_AXI.v \
$(SOURCE_PATH)/Base/src/reset_delay.v \
$(SOURCE_PATH)/Base/src/control_regs.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/sim/design_1_blk_mem_gen_0_0.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/sim/design_1_rst_clk_wiz_0_100M_0.vhd \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_pl_controller_0_0/sim/design_1_pl_controller_0_0.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_control_wrapper_0_0/sim/design_1_control_wrapper_0_0.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_control_regs_0_0/sim/design_1_control_regs_0_0.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_0/sim/bd_88fd_one_0.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/sim/bd_88fd_psr_aclk_0.vhd \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_2/sim/bd_88fd_arinsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_3/sim/bd_88fd_rinsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_4/sim/bd_88fd_awinsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/sim/bd_88fd_winsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/sim/bd_88fd_binsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_7/sim/bd_88fd_aroutsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_8/sim/bd_88fd_routsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_9/sim/bd_88fd_awoutsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_10/sim/bd_88fd_woutsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/sim/bd_88fd_boutsw_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_12/sim/bd_88fd_arni_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_13/sim/bd_88fd_rni_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_14/sim/bd_88fd_awni_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_15/sim/bd_88fd_wni_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_16/sim/bd_88fd_bni_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_17/sim/bd_88fd_s00mmu_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_18/sim/bd_88fd_s00tr_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_19/sim/bd_88fd_s00sic_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_20/sim/bd_88fd_s00a2s_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_21/sim/bd_88fd_sarn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_22/sim/bd_88fd_srn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_23/sim/bd_88fd_sawn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_24/sim/bd_88fd_swn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_25/sim/bd_88fd_sbn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_26/sim/bd_88fd_s01mmu_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_27/sim/bd_88fd_s01tr_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_28/sim/bd_88fd_s01sic_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_29/sim/bd_88fd_s01a2s_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_30/sim/bd_88fd_sarn_1.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_31/sim/bd_88fd_srn_1.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_32/sim/bd_88fd_sawn_1.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_33/sim/bd_88fd_swn_1.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_34/sim/bd_88fd_sbn_1.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_35/sim/bd_88fd_m00s2a_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_36/sim/bd_88fd_m00arn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_37/sim/bd_88fd_m00rn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_38/sim/bd_88fd_m00awn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_39/sim/bd_88fd_m00wn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_40/sim/bd_88fd_m00bn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_41/sim/bd_88fd_m00e_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_42/sim/bd_88fd_m01s2a_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_43/sim/bd_88fd_m01arn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_44/sim/bd_88fd_m01rn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_45/sim/bd_88fd_m01awn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_46/sim/bd_88fd_m01wn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_47/sim/bd_88fd_m01bn_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_48/sim/bd_88fd_m01e_0.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/sim/bd_88fd.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/sim/design_1_smartconnect_1_0.v \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.gen/sources_1/bd/design_1/sim/design_1.v \
$(SOURCE_PATH)/Base/src/design_1_wrapper.v \
$(SOURCE_PATH)/Base/tb/tb_top.sv \
$(SOURCE_PATH)/Base/vivado/hackathon/hackathon.sim/sim_1/behav/questa/glbl.v

###
help:
	@echo "Available commands"
	@echo "make batch - compile optimize and simulate in terminal"
	@echo "make gui - run simulation in gui"
	@echo "make gui_visualizer - run visualizer gui (is better)"
	@echo "make compile - just compilation"
	@echo "make optimize - just optimize"
	@echo "make simulate - just simulate"

batch: compile optimize simulate
gui: simulate_gui

compile:
	$(QRUN) -compile -top tb_top -top glbl $(SWITCHES) $(LIBS) $(COMPILATION_BASE)
optimize:
	$(QRUN) -optimize -top tb_top -top glbl $(SWITCHES) $(LIBS) $(COMPILATION_BASE) 
simulate:
	$(QRUN) -simulate -top tb_top -top glbl $(SWITCHES) $(LIBS) $(COMPILATION_BASE)

### THIS TARGET HERE WILL RUN GUI MODE FOR SIMULATION
simulate_gui:
	$(QRUN) -gui=interactive -top tb_top -top glbl $(SWITCHES) $(LIBS) $(COMPILATION_BASE)

gui_visualizer:
	$(QRUN) -visualizer -gui=interactive -debug,livesim -top tb_top -top glbl $(SWITCHES) $(LIBS) $(COMPILATION_BASE)
